/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package passportsystem;

import java.io.File;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author Acer
 */
public class Application extends javax.swing.JFrame {
    private int ApplicantID;

   
 
    /**
     * Creates new form Application
     */
    public Application() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        SERVICEBTNG = new javax.swing.ButtonGroup();
        TDOCBTNG = new javax.swing.ButtonGroup();
        GENDERBTNG = new javax.swing.ButtonGroup();
        MARITALBTNGG = new javax.swing.ButtonGroup();
        YESBTNG = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        TYPESLBL = new javax.swing.JLabel();
        TYPEDLBL = new javax.swing.JLabel();
        GNLBL = new javax.swing.JLabel();
        SNLBL = new javax.swing.JLabel();
        PALBL = new javax.swing.JLabel();
        ANICLBL = new javax.swing.JLabel();
        DISTRICTLBL = new javax.swing.JLabel();
        PROVINCELBL = new javax.swing.JLabel();
        DOBLBL = new javax.swing.JLabel();
        GENDERLBL = new javax.swing.JLabel();
        PROFELBL = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        CONLBL = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        DCNOLBL = new javax.swing.JLabel();
        DOBTF = new javax.swing.JTextField();
        CONTNOTF = new javax.swing.JTextField();
        ADDRESSTF = new javax.swing.JTextField();
        NAMETF = new javax.swing.JTextField();
        AFNICTF = new javax.swing.JTextField();
        PROFETF = new javax.swing.JTextField();
        ONEDAYBTN = new javax.swing.JRadioButton();
        NORMALBTN = new javax.swing.JRadioButton();
        ECBTN = new javax.swing.JRadioButton();
        ICBTN = new javax.swing.JRadioButton();
        ALLBTN = new javax.swing.JRadioButton();
        MEBTN = new javax.swing.JRadioButton();
        SNAMETF = new javax.swing.JTextField();
        PROVINCE = new javax.swing.JComboBox<>();
        DISTRICT = new javax.swing.JComboBox<>();
        DUALCNOTF = new javax.swing.JTextField();
        YESBTN = new javax.swing.JRadioButton();
        NOBTN = new javax.swing.JRadioButton();
        MARRIEDBTN = new javax.swing.JRadioButton();
        UNMARRIEDBTN = new javax.swing.JRadioButton();
        MAILTF = new javax.swing.JTextField();
        MAILLBL = new javax.swing.JLabel();
        APLBL = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        SDLBL = new javax.swing.JLabel();
        DOCTF = new javax.swing.JTextField();
        DOCUMENTBTN = new javax.swing.JButton();
        MALEBTN = new javax.swing.JRadioButton();
        FEMALEBTN = new javax.swing.JRadioButton();
        SUBMITBTN = new javax.swing.JButton();
        BACKBTN = new javax.swing.JButton();
        EXITBTN = new javax.swing.JButton();
        AFPLBL = new javax.swing.JLabel();
        NICLBL = new javax.swing.JLabel();
        NICTF = new javax.swing.JTextField();
        VERIFYLBL = new javax.swing.JLabel();
        VERIFYBTN = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Application");
        setLocation(new java.awt.Point(0, 0));
        setLocationByPlatform(true);
        setSize(new java.awt.Dimension(2000, 1000));

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);
        jScrollPane1.setPreferredSize(new java.awt.Dimension(1980, 1080));

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));

        jPanel2.setBackground(new java.awt.Color(0, 204, 204));

        TYPESLBL.setText("01.Type of Service ");

        TYPEDLBL.setText("02.Type of Travel  Document");

        GNLBL.setText("03.Given Name(First Name Followed By Middle Name)");

        SNLBL.setText("04.Surname");

        PALBL.setText("06.Permenant Address");

        ANICLBL.setText("05.National Identity Card No");

        DISTRICTLBL.setText("6.2 District");

        PROVINCELBL.setText("6.1.Provice");

        DOBLBL.setText("07.Date Of Birth");

        GENDERLBL.setText("08.Gender");

        PROFELBL.setText("09.Profession");

        jLabel15.setText("12.Marital Status");

        CONLBL.setText("10.Contact No");

        jLabel18.setText("13.Do You Have Dual Citizenship ?");

        DCNOLBL.setText("13.1.Dual Citizenship No");

        DOBTF.setEditable(false);
        DOBTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DOBTFActionPerformed(evt);
            }
        });

        CONTNOTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CONTNOTFActionPerformed(evt);
            }
        });

        ADDRESSTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ADDRESSTFActionPerformed(evt);
            }
        });

        NAMETF.setEditable(false);
        NAMETF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NAMETFActionPerformed(evt);
            }
        });

        AFNICTF.setEditable(false);
        AFNICTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AFNICTFActionPerformed(evt);
            }
        });

        PROFETF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PROFETFActionPerformed(evt);
            }
        });

        SERVICEBTNG.add(ONEDAYBTN);
        ONEDAYBTN.setText("One Day");

        SERVICEBTNG.add(NORMALBTN);
        NORMALBTN.setText("Normal");
        NORMALBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NORMALBTNActionPerformed(evt);
            }
        });

        TDOCBTNG.add(ECBTN);
        ECBTN.setText("Emergency Certificate");
        ECBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ECBTNActionPerformed(evt);
            }
        });

        TDOCBTNG.add(ICBTN);
        ICBTN.setText("Identity Certificate");

        TDOCBTNG.add(ALLBTN);
        ALLBTN.setText("All countries");

        TDOCBTNG.add(MEBTN);
        MEBTN.setText("Middle East Countries");
        MEBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MEBTNActionPerformed(evt);
            }
        });

        SNAMETF.setEditable(false);
        SNAMETF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SNAMETFActionPerformed(evt);
            }
        });

        PROVINCE.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Central Province", "Eastern Province", "North Central Province", "Northern Province", "North Western Province", "Sabaragamuwa Province", "Southern Province", "Uva Province", "Western Province" }));

        DISTRICT.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ampara", "Anuradhapura", "Badulla", "Batticaloa", "Colombo", "Galle", "Gampaha", "Hambantota", "Jaffna", "Kalutara", "Kandy", "Kegalle", "Kilinochchi", "Kurunegala", "Mannar", "Matale", "Matara", "Moneragala", "Mullaitivu", "Nuwara Eliya", "Polonnaruwa", "Puttalam", "Ratnapura", "Trincomalee", "Vavuniya" }));

        DUALCNOTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DUALCNOTFActionPerformed(evt);
            }
        });

        YESBTNG.add(YESBTN);
        YESBTN.setText("Yes");

        YESBTNG.add(NOBTN);
        NOBTN.setText("No");

        MARITALBTNGG.add(MARRIEDBTN);
        MARRIEDBTN.setText("Married");

        MARITALBTNGG.add(UNMARRIEDBTN);
        UNMARRIEDBTN.setText("Unmarried");

        MAILTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MAILTFActionPerformed(evt);
            }
        });

        MAILLBL.setText("11.E-mail");

        APLBL.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        APLBL.setText("Application Form ");

        jPanel3.setBackground(new java.awt.Color(0, 210, 190));

        SDLBL.setText("14.Submit Document");

        DOCTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DOCTFActionPerformed(evt);
            }
        });

        DOCUMENTBTN.setText("Submit Your Documents here");
        DOCUMENTBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DOCUMENTBTNActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(SDLBL, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(152, 152, 152)
                .addComponent(DOCTF, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(DOCUMENTBTN)
                .addGap(67, 67, 67))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(DOCTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(DOCUMENTBTN))
                    .addComponent(SDLBL))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        GENDERBTNG.add(MALEBTN);
        MALEBTN.setText("MALE");
        MALEBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MALEBTNActionPerformed(evt);
            }
        });

        GENDERBTNG.add(FEMALEBTN);
        FEMALEBTN.setText("FEMALE");

        SUBMITBTN.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        SUBMITBTN.setText("SUBMIT");
        SUBMITBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SUBMITBTNActionPerformed(evt);
            }
        });

        BACKBTN.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        BACKBTN.setText("Back");
        BACKBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BACKBTNActionPerformed(evt);
            }
        });

        EXITBTN.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        EXITBTN.setText("Exit");
        EXITBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EXITBTNActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(PROFELBL, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(TYPEDLBL, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(ALLBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(TYPESLBL, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(81, 81, 81)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(ONEDAYBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addComponent(MEBTN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(APLBL, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(42, 42, 42))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(52, 52, 52)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(DISTRICTLBL, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(PROVINCELBL, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(PROVINCE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(MARRIEDBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(DISTRICT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(UNMARRIEDBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(116, 116, 116))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(GNLBL, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(SNLBL, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(PALBL, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ANICLBL, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(DOBLBL, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(GENDERLBL, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(MALEBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(82, 82, 82)
                                        .addComponent(FEMALEBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(MAILLBL, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(CONLBL, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(36, 36, 36)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(SNAMETF, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(NAMETF, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(AFNICTF, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(ADDRESSTF, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(PROFETF, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(CONTNOTF, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(DOBTF, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(MAILTF, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(DUALCNOTF, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ECBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(39, 39, 39)
                                .addComponent(ICBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(1089, 1089, 1089))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(NOBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(YESBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(1601, 1601, 1601))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(729, 729, 729)
                .addComponent(SUBMITBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(94, 94, 94)
                        .addComponent(DCNOLBL, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(BACKBTN)
                                .addGap(26, 26, 26)
                                .addComponent(EXITBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(248, 248, 248)
                    .addComponent(NORMALBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(APLBL)
                .addGap(42, 42, 42)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TYPESLBL)
                    .addComponent(ONEDAYBTN))
                .addGap(33, 33, 33)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(TYPEDLBL)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(ALLBTN)
                                .addComponent(MEBTN)
                                .addComponent(ECBTN)
                                .addComponent(ICBTN)))
                        .addGap(35, 35, 35)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(GNLBL)
                            .addComponent(NAMETF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(SNLBL)
                        .addGap(6, 6, 6))
                    .addComponent(SNAMETF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AFNICTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ANICLBL))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ADDRESSTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PALBL))
                .addGap(11, 11, 11)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PROVINCE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PROVINCELBL))
                .addGap(26, 26, 26)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DISTRICT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DISTRICTLBL))
                .addGap(28, 28, 28)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(DOBLBL)
                    .addComponent(DOBTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(GENDERLBL, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(MALEBTN)
                    .addComponent(FEMALEBTN))
                .addGap(25, 25, 25)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PROFELBL)
                    .addComponent(PROFETF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CONLBL, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CONTNOTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(MAILLBL, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(MAILTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(MARRIEDBTN)
                    .addComponent(UNMARRIEDBTN))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(YESBTN)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(NOBTN)
                .addGap(19, 19, 19)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(DCNOLBL, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DUALCNOTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SUBMITBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BACKBTN)
                    .addComponent(EXITBTN))
                .addGap(26, 26, 26))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(73, 73, 73)
                    .addComponent(NORMALBTN)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        AFPLBL.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        AFPLBL.setText("Apply For the Passport");

        NICLBL.setText("Enter Your NIC");

        NICTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NICTFActionPerformed(evt);
            }
        });

        VERIFYLBL.setText("(Verify you are a citizen)");

        VERIFYBTN.setText("Verify");
        VERIFYBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VERIFYBTNActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addComponent(NICLBL, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(NICTF, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(66, 66, 66)
                        .addComponent(VERIFYBTN))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(197, 197, 197)
                        .addComponent(VERIFYLBL, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(352, 352, 352)
                        .addComponent(AFPLBL, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(AFPLBL, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NICLBL)
                    .addComponent(NICTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(VERIFYBTN))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(VERIFYLBL)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jScrollPane1.setViewportView(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 999, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void NICTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NICTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NICTFActionPerformed

    private void DOBTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DOBTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DOBTFActionPerformed

    private void CONTNOTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CONTNOTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CONTNOTFActionPerformed

    private void ADDRESSTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ADDRESSTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ADDRESSTFActionPerformed

    private void NAMETFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NAMETFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NAMETFActionPerformed

    private void AFNICTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AFNICTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AFNICTFActionPerformed

    private void PROFETFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PROFETFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PROFETFActionPerformed

    private void SNAMETFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SNAMETFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SNAMETFActionPerformed

    private void DUALCNOTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DUALCNOTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DUALCNOTFActionPerformed

    private void MAILTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MAILTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MAILTFActionPerformed

    private void NORMALBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NORMALBTNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NORMALBTNActionPerformed

    private void MEBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MEBTNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MEBTNActionPerformed

    private void ECBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ECBTNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ECBTNActionPerformed

    private void MALEBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MALEBTNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MALEBTNActionPerformed

    private void VERIFYBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VERIFYBTNActionPerformed
               
    // Assuming Application is the name of your Application class
   // Create an instance of the Application class
    
    // Call the method to retrieve applicant data based on NIC
    String NIC = NICTF.getText();
    Applicant applicant  = new Applicant  ();
    applicant.applicationAutoFill(NIC,AFNICTF, NAMETF, SNAMETF, DOBTF);
    // Additional code to handle submission



  
    }//GEN-LAST:event_VERIFYBTNActionPerformed

    private void SUBMITBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SUBMITBTNActionPerformed
        // TODO add your handling code here:
        

String NIC = AFNICTF.getText();
String givenName = NAMETF.getText();
String surname = SNAMETF.getText();
String permanentAddress = ADDRESSTF.getText();
String dateOfBirth = DOBTF.getText(); // Assuming dateOfBirth is a String representation
String profession = PROFETF.getText();
String contactNo =CONTNOTF.getText();
String email = MAILTF.getText();
String dualCitizenNo = DUALCNOTF.getText();
String submitDocument = DOCTF.getText();
String district = (String) PROVINCE.getSelectedItem();
String province = (String) DISTRICT.getSelectedItem();

String typeOfService = "";
if (NORMALBTN.isSelected()) {
    typeOfService = NORMALBTN.getText();
} else if (ONEDAYBTN.isSelected()) {
    typeOfService = ONEDAYBTN.getText();
}

String typeOfTravelDocument = "";
if (ALLBTN.isSelected()) {
    typeOfTravelDocument = ALLBTN.getText();
} else if (MEBTN.isSelected()) {
    typeOfTravelDocument =MEBTN.getText();
} 
else if (ECBTN.isSelected()) {
    typeOfTravelDocument =ECBTN.getText();
} 
else if (ICBTN.isSelected()) {
    typeOfTravelDocument =ICBTN.getText();
} 

String gender = "";
if (MALEBTN.isSelected()) {
    gender = MALEBTN.getText();
} else if (FEMALEBTN.isSelected()) {
    gender = FEMALEBTN.getText();
} // Add more conditions for additional gender radio buttons if needed

String maritalStatus = "";
if (MARRIEDBTN.isSelected()) {
    maritalStatus = MARRIEDBTN.getText();
} else if (UNMARRIEDBTN.isSelected()) {
    maritalStatus =UNMARRIEDBTN.getText();
} // Add more conditions for additional marital status radio buttons if needed

String dualCitizenStatus = "";
if (YESBTN.isSelected()) {
    dualCitizenStatus = YESBTN.getText();
} else if (NOBTN.isSelected()) {
    dualCitizenStatus = NOBTN.getText();
} // Add more conditions 

        Applicant applicant = new Applicant  ();
        int ApplicationID = applicant.insertData(typeOfService, typeOfTravelDocument, NIC, givenName, surname, permanentAddress, district, dateOfBirth, gender, profession, contactNo, email, maritalStatus, dualCitizenStatus, dualCitizenNo, submitDocument, province);
        
        
        if (ApplicationID != -1) {
        // Display a success message with the generated registration ID
        String successMessage = "Application is successfully submitted. Your Application ID is: " + ApplicationID+"\n (please remember you Application ID ";
        JOptionPane.showMessageDialog(this, successMessage, "Success", JOptionPane.INFORMATION_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(this, "Submission failed.", "Error", JOptionPane.ERROR_MESSAGE);
        }
        
        
        
        
    }//GEN-LAST:event_SUBMITBTNActionPerformed

    private void DOCUMENTBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DOCUMENTBTNActionPerformed
        // TODO add your handling code here:
        
        JFileChooser chooser = new JFileChooser();
        chooser.showOpenDialog(null);
        File f = chooser.getSelectedFile();
        String filename = f.getAbsolutePath();
        DOCTF.setText(filename);
        
    }//GEN-LAST:event_DOCUMENTBTNActionPerformed

    private void EXITBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EXITBTNActionPerformed
        // TODO add your handling code here:
        int response =  JOptionPane.showConfirmDialog(null,
                        "DO YOU WANT TO EXIT?", "Exit Confirmation",
                        JOptionPane.YES_NO_OPTION);
        
        //if click on yes,clear fields
				if(response ==JOptionPane.YES_OPTION ) {
                                    this.dispose();
                                }
    }//GEN-LAST:event_EXITBTNActionPerformed

    private void BACKBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BACKBTNActionPerformed
        // TODO add your handling code here:
        ApplicantHome homepage1 = new ApplicantHome();
        homepage1.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BACKBTNActionPerformed

    private void DOCTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DOCTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DOCTFActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Application.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Application.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Application.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Application.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Application().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ADDRESSTF;
    private javax.swing.JTextField AFNICTF;
    private javax.swing.JLabel AFPLBL;
    private javax.swing.JRadioButton ALLBTN;
    private javax.swing.JLabel ANICLBL;
    private javax.swing.JLabel APLBL;
    private javax.swing.JButton BACKBTN;
    private javax.swing.JLabel CONLBL;
    private javax.swing.JTextField CONTNOTF;
    private javax.swing.JLabel DCNOLBL;
    private javax.swing.JComboBox<String> DISTRICT;
    private javax.swing.JLabel DISTRICTLBL;
    private javax.swing.JLabel DOBLBL;
    private javax.swing.JTextField DOBTF;
    private javax.swing.JTextField DOCTF;
    private javax.swing.JButton DOCUMENTBTN;
    private javax.swing.JTextField DUALCNOTF;
    private javax.swing.JRadioButton ECBTN;
    private javax.swing.JButton EXITBTN;
    private javax.swing.JRadioButton FEMALEBTN;
    private javax.swing.ButtonGroup GENDERBTNG;
    private javax.swing.JLabel GENDERLBL;
    private javax.swing.JLabel GNLBL;
    private javax.swing.JRadioButton ICBTN;
    private javax.swing.JLabel MAILLBL;
    private javax.swing.JTextField MAILTF;
    private javax.swing.JRadioButton MALEBTN;
    private javax.swing.ButtonGroup MARITALBTNGG;
    private javax.swing.JRadioButton MARRIEDBTN;
    private javax.swing.JRadioButton MEBTN;
    private javax.swing.JTextField NAMETF;
    private javax.swing.JLabel NICLBL;
    private javax.swing.JTextField NICTF;
    private javax.swing.JRadioButton NOBTN;
    private javax.swing.JRadioButton NORMALBTN;
    private javax.swing.JRadioButton ONEDAYBTN;
    private javax.swing.JLabel PALBL;
    private javax.swing.JLabel PROFELBL;
    private javax.swing.JTextField PROFETF;
    private javax.swing.JComboBox<String> PROVINCE;
    private javax.swing.JLabel PROVINCELBL;
    private javax.swing.JLabel SDLBL;
    private javax.swing.ButtonGroup SERVICEBTNG;
    private javax.swing.JTextField SNAMETF;
    private javax.swing.JLabel SNLBL;
    private javax.swing.JButton SUBMITBTN;
    private javax.swing.ButtonGroup TDOCBTNG;
    private javax.swing.JLabel TYPEDLBL;
    private javax.swing.JLabel TYPESLBL;
    private javax.swing.JRadioButton UNMARRIEDBTN;
    private javax.swing.JButton VERIFYBTN;
    private javax.swing.JLabel VERIFYLBL;
    private javax.swing.JRadioButton YESBTN;
    private javax.swing.ButtonGroup YESBTNG;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
